# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  scheduledjobrunner:
    image: scheduledjobrunner
    build:
      context: .
      dockerfile: scheduledjobrunner/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5116:5116
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
